### PR TITLE
remove duplicated quiz entry for OP_CHECKMULTISIG

### PR DESCRIPTION
**Pull request by ptisserand**
Quiz entry for OP_CHECKMULTISIG was dpulicated

### CODE REVIEW

**Comment by jrakibi** [comment]
Hey @ptisserand, thanks for the contribution! 

I checked the quiz entry for OP_CHECKMULTISIG but didn’t notice the duplicate https://bitcoindevs.xyz/decoding/3-7-overview-quiz

Could you provide a bit more context or point me to the specific part you’re referring to? That would help a lot in resolving the issue

**Comment by ptisserand** [comment]
Hi @jrakibi see attached screenshot for https://bitcoindevs.xyz/decoding/3-7-overview-quiz



Here is the duplicated entries:
https://github.com/bitcoin-dev-project/decoding-bitcoin/blob/6ebddf7c4792b17e51e0f5c22476d6a4ee6ff89a/decoding/3-7-overview-quiz.mdx?plain=1#L18-L31
https://github.com/bitcoin-dev-project/decoding-bitcoin/blob/6ebddf7c4792b17e51e0f5c22476d6a4ee6ff89a/decoding/3-7-overview-quiz.mdx?plain=1#L313-L326

**Review by jrakibi — APPROVED** [review]

**Comment by jrakibi** [comment]
Ooh yes thanks for pointing this out, great catch

**Comment by jrakibi** [comment]
merged

**Pull request merged**
